Repository DragonBlood007/New-Repo, pull requests merged in 2020-10, with the labels that each got.

#1 pfft
  Kaise karte hai bc foss
Labels: hacktoberfest

#2 create mail
  Mail
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#3 updated
  Extract_combine.py
Labels: hacktoberfest-accepted

#4 update html
  Html_script.py
Labels: hacktoberfest, hacktoberfest-accepted

#12 Update README.md ;)
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#17 Updated file with contributors.
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#15 Update html_script.py
  Html_script.py
Labels: hacktoberfest, hacktoberfest-accepted

#21 Create twosat.hpp
  twosat.hpp
Labels: hacktoberfest, hacktoberfest-accepted

#20 Create trie.hpp
  trie.hpp
Labels: hacktoberfest, hacktoberfest-accepted

#19 Update Html_script.py
  Html_script.py
Labels: hacktoberfest, hacktoberfest-accepted

#18 Update Extract_combine.py
  Extract_combine.py
Labels: hacktoberfest, hacktoberfest-accepted

#23 Update A
  a
Labels: hacktoberfest, hacktoberfest-accepted

#24 Updated
  Kaise karte hai bc foss
Labels: hacktoberfest, hacktoberfest-accepted

#25 Update the file
  debug code
Labels: hacktoberfest, hacktoberfest-accepted

#26 Updated html.script
  Html_script.py
Labels: hacktoberfest, hacktoberfest-accepted

#28 adding scripts of bootsrap in body section
  a
Labels: hacktoberfest, hacktoberfest-accepted

#29 Code for dijikstra algorithm
  Dijikstra.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#30 trie with unordered_map
  trie.hpp
Labels: hacktoberfest, hacktoberfest-accepted

#31 adding one more name in list :)
  README.md
Labels: hacktoberfest, hacktoberfest-accepted
